export const ADMINISTRATIVE_USERS_SERVICE = Symbol('ADMINISTRATIVE_USERS_SERVICE');
export const ACTIVITY_SERVICE = Symbol('ACTIVITY_SERVICE');
export const ADMINISTRATIVE_APPLICATIONS_SERVICE = Symbol('ADMINISTRATIVE_APPLICATIONS_SERVICE');
export const ADMINISTRATIVE_APPLICATION_ACCESS_SERVICE = Symbol(
  'ADMINISTRATIVE_APPLICATION_ACCESS_SERVICE',
);
