export const GOOGLE_OAUTH_SERVICE = Symbol('GOOGLE_OAUTH_SERVICE');
export const OAUTH_LOGIN_ATTEMPTS_SERVICE = Symbol('OAUTH_LOGIN_ATTEMPTS_SERVICE');
export const USER_SESSIONS_SERVICE = Symbol('USER_SESSIONS_SERVICE');
export const USERS_SERVICE = Symbol('USERS_SERVICE');
export const AUTH_PRISMA_SERVICE = Symbol('AUTH_PRISMA_SERVICE');
export const AUTH_AUDIT_EVENTS_SERVICE = Symbol('AUTH_AUDIT_EVENTS_SERVICE');
